# Generated by Django 3.0.5 on 2020-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(max_length=200)),
                ('blog_field', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
